import {defineConfig} from 'oxlint'

export default defineConfig({
	plugins: [
		'eslint',
		'typescript',
		'unicorn',
		'react',
		'react-perf',
		'vue',
		'oxc',
		'import',
		'jsdoc',
		'jsx-a11y',
		'node',
		'promise',
		'vitest',
	],
	categories: {
		correctness: 'warn',
		suspicious: 'warn',
		perf: 'warn',
	},
	rules: {
		'import/no-cycle': 'error',
		'import/no-duplicates': 'error',
		'eslint/sort-imports': 'allow',
		'eslint/no-unused-private-class-members': 'error',
		'eslint/no-unused-vars': 'error',
		'eslint/no-shadow': 'off',
		'eslint/no-throw-literal': 'warn',
		'eslint/no-await-in-loop': 'off',
		'eslint/object-shorthand': 'error',
		'typescript/consistent-type-imports': 'error',
		'typescript/consistent-type-exports': 'error',
		'typescript/no-explicit-any': 'error',
		'typescript/no-useless-default-assignment': 'warn',
		'typescript/prefer-readonly': 'warn',
		'typescript/prefer-find': 'warn',
		'typescript/no-unnecessary-qualifier': 'warn',
		// TODO(ts7): re-enable with the TS 7 migration. tsgolint judges this rule with the TS 7 checker while
		// builds use TS 6, so it flags casts TS 6 requires (build breaks) or that drive generic inference
		// (silent type widening, e.g. PropsModel.layout) — every finding needs manual vetting until checkers align.
		'typescript/no-unnecessary-type-assertion': 'off',
		'typescript/no-non-null-assertion': 'error',
		'typescript/no-dynamic-delete': 'warn',
		'typescript/no-unsafe-type-assertion': 'error',
		'typescript/dot-notation': 'warn',
		'typescript/no-unnecessary-type-parameters': 'warn',
		'typescript/no-unnecessary-type-arguments': 'off',
		'typescript/no-redundant-type-constituents': 'off',
		'typescript/consistent-return': 'off',
		'typescript/no-unnecessary-condition': 'error',
		'typescript/switch-exhaustiveness-check': 'warn',
		'typescript/prefer-optional-chain': 'warn',
		'typescript/prefer-nullish-coalescing': 'warn',
		'typescript/no-misused-promises': 'warn',
		'typescript/no-unsafe-argument': 'error',
		'typescript/no-unsafe-assignment': 'off',
		'typescript/no-unsafe-call': 'error',
		'typescript/no-unsafe-member-access': 'error',
		'typescript/no-unsafe-return': 'error',
		'unicorn/no-useless-spread': 'warn',
		'unicorn/prefer-module': 'warn',
		'unicorn/prefer-ternary': 'warn',
		'unicorn/consistent-function-scoping': 'off',
		'react/no-children-prop': 'allow',
		'react/exhaustive-deps': 'off',
		'react/react-in-jsx-scope': 'off',
		'react-perf/jsx-no-new-object-as-prop': 'off',
		'react-perf/jsx-no-new-function-as-prop': 'off',
		'jsx_a11y/click-events-have-key-events': 'off',
		'vitest/valid-expect-in-promise': 'warn',
		'vitest/require-mock-type-parameters': 'off',
		'vitest/warn-todo': 'off',
		'vitest/valid-expect': 'off',
		'vitest/no-disabled-tests': 'off',
		'vitest/expect-expect': 'off',
		'eslint/no-underscore-dangle': 'off',
		'jsx_a11y/no-noninteractive-element-interactions': 'off',
		'react-perf/jsx-no-jsx-as-prop': 'off',
		'react-perf/jsx-no-new-array-as-prop': 'off',
		'import/no-unassigned-import': ['warn', {allow: ['**/*.css']}],
	},
	overrides: [
		{
			files: [
				'**/*.spec.ts',
				'**/*.spec.tsx',
				'**/*.spec.react.tsx',
				'**/*.stories.ts',
				'**/*.stories.tsx',
				'**/*.stories.react.tsx',
				'**/*.bench.ts',
				'**/*.js',
			],
			rules: {
				'react/no-unstable-nested-components': 'off',
				'typescript/no-explicit-any': 'off',
				'typescript/no-non-null-assertion': 'off',
				'typescript/no-unsafe-argument': 'off',
				'typescript/no-unsafe-assignment': 'off',
				'typescript/no-unsafe-call': 'off',
				'typescript/no-unsafe-member-access': 'off',
				'typescript/no-unsafe-return': 'off',
				'typescript/unbound-method': 'off',
			},
		},
		{
			files: ['**/*.vue'],
			rules: {
				'eslint/no-unused-expressions': 'off',
			},
		},
		{
			files: ['**/vitest.setup*.ts'],
			rules: {
				'typescript/no-unsafe-call': 'off',
			},
		},
		{
			files: ['**/vite.config.ts'],
			rules: {
				'typescript/no-unsafe-call': 'off',
			},
		},
	],
	ignorePatterns: ['packages/website/**', 'packages/core/src/shared/signals/alien-signals/**'],
	settings: {
		jsdoc: {
			ignorePrivate: false,
			ignoreInternal: false,
			ignoreReplacesDocs: true,
			overrideReplacesDocs: true,
			augmentsExtendsReplacesDocs: false,
			implementsReplacesDocs: false,
			exemptDestructuredRootsFromChecks: false,
			tagNamePreference: {},
		},
	},
	env: {
		builtin: true,
	},
	options: {
		typeAware: true,
		typeCheck: false,
		denyWarnings: true,
		reportUnusedDisableDirectives: 'deny',
	},
})