packages:
    - packages/**/*

catalog:
    '@faker-js/faker': ^10.2.0
    '@microsoft/api-extractor': ^7.57.2
    '@storybook/addon-docs': ^10.2.3
    '@storybook/addon-links': ^10.2.3
    '@storybook/cli': ^10.2.3
    '@storybook/react-vite': ^10.2.3
    '@storybook/vue3-vite': ^10.2.3
    '@types/node': ^24.10.1
    '@types/react': ^19.2.14
    '@types/react-dom': ^19.2.3
    '@vitejs/plugin-react-swc': ^4.2.3
    '@vitejs/plugin-vue': ^6.0.4
    '@vitest/browser-playwright': ^4.0.18
    '@vitest/coverage-v8': ^4.0.18
    '@vitest/ui': ^4.0.18
    playwright: ^1.58.2
    react: ^19.2.4
    react-dom: ^19.2.4
    storybook: ^10.2.3
    typescript: ^5.9.3
    vite: ^7.3.1
    vitest: ^4.0.18
    vitest-browser-react: ^2.0.5
    vitest-browser-vue: ^2.0.2
    vue: ^3.5.13
    vue-tsc: ^3.2.5
