packages:
    - packages/**/*

catalog:
    '@faker-js/faker': ^10.2.0
    '@microsoft/api-extractor': ^7.57.7
    '@storybook/addon-docs': ^10.2.19
    '@storybook/addon-links': ^10.2.19
    '@storybook/cli': ^10.2.19
    '@storybook/react-vite': ^10.2.19
    '@storybook/vue3-vite': ^10.2.19
    '@types/node': ^24.10.1
    '@types/react': ^19.2.14
    '@types/react-dom': ^19.2.3
    '@vitejs/plugin-react-swc': ^4.3.0
    '@vitejs/plugin-vue': ^6.0.5
    '@vitest/browser-playwright': ^4.1.0
    '@vitest/coverage-v8': ^4.1.0
    '@vitest/ui': ^4.1.0
    playwright: ^1.58.2
    react: ^19.2.4
    react-dom: ^19.2.4
    storybook: ^10.2.19
    typescript: ^5.9.3
    vite: ^8.0.0
    vitest: ^4.1.0
    vitest-browser-react: ^2.1.0
    vitest-browser-vue: ^2.1.0
    vue: ^3.5.30
    vue-tsc: ^3.2.5
