export {Parser, SegmentMatcherType} from './Parser'
export type {Token, TextToken, MarkToken, Markup} from './types'
export type {MarkupDescriptor} from './core/MarkupDescriptor'
export {PLACEHOLDER} from './constants'
export {annotate} from './utils/annotate'
export {denote} from './utils/denote'
export {toString} from './utils/toString'
export {RegexSegmentMatcher} from './utils/RegexSegmentMatcher'
export {IndexOfSegmentMatcher} from './utils/IndexOfSegmentMatcher'
