export type {InnerOption} from './src/features/default/types'

export {assertAnnotated, assertNonNullable} from './src/shared/checkers'
export {annotate} from './src/features/parsing/Parser/annotate'
export {isAnnotated} from './src/shared/checkers'

export {KEYBOARD, wordRegex} from './src/shared/constants'
export type {label, value, MarkMatch, Markup, MarkStruct, OverlayMatch} from './src/shared/types'

export {Parser} from './src/features/parsing/Parser/Parser'
export {denote} from './src/features/parsing/denote'
export {escape} from './src/features/parsing/Parser/escape'
export {toString} from './src/utils/functions/toString'
export {shallow} from './src/utils/functions/shallow'
export {createNewSpan} from './src/utils/functions/createNewSpan'
export {deleteMark} from './src/utils/functions/deleteMark'
export {getTokensByValue} from './src/features/parsing/getTokensByValue'
export {getTokensByUI} from './src/features/parsing/getTokensByUI'
export {findGap} from './src/features/preparsing/utils/findGap'
export {getClosestIndexes} from './src/features/preparsing/utils/getClosestIndexes'

export {PLACEHOLDER} from './src/shared/constants'
export type {EventKey} from './src/shared/types'
export type {Listener} from './src/shared/types'
export {SystemEvent} from './src/shared/constants'
export type {InnerMarkedInputProps} from './src/features/default/types'
export {Store} from './src/utils/classes/Store'
export {Caret} from './src/utils/classes/Caret'
export {TriggerFinder} from './src/utils/classes/TriggerFinder'
export type {OverlayTrigger} from './src/shared/types'
export {DEFAULT_CLASS_NAME, DEFAULT_MARKUP, DEFAULT_OPTIONS, DEFAULT_TRIGGER} from './src/features/default/constants'
