export type {InnerOption} from './src/features/default/types'

export {assertAnnotated, assertNonNullable} from './src/shared/checkers'
export {annotate} from './src/features/parsing/Parser/annotate'
export {isAnnotated} from './src/shared/checkers'

export {KEYBOARD, wordRegex} from './src/shared/constants'
export type {label, value, MarkMatch, Markup, MarkStruct, OverlayMatch} from './src/shared/types'

export {Parser} from './src/features/parsing/Parser/Parser'
export {denote} from './src/features/parsing/denote'
export {escape} from './src/features/parsing/Parser/escape'
export {toString, shallow, createNewSpan, deleteMark} from './src/features/text-manipulation'
export {getTokensByValue} from './src/features/parsing/getTokensByValue'
export {getTokensByUI} from './src/features/parsing/getTokensByUI'
export {findGap} from './src/features/preparsing/utils/findGap'
export {getClosestIndexes} from './src/features/preparsing/utils/getClosestIndexes'

export {PLACEHOLDER} from './src/shared/constants'
export type {EventKey} from './src/shared/types'
export type {Listener} from './src/shared/types'
export {SystemEvent} from './src/features/events'
export type {InnerMarkedInputProps} from './src/features/default/types'
export {Store} from './src/features/store'
export {Caret} from './src/features/caret'
export {TriggerFinder} from './src/features/caret'
export type {OverlayTrigger} from './src/shared/types'
export {DEFAULT_CLASS_NAME, DEFAULT_MARKUP, DEFAULT_OPTIONS, DEFAULT_TRIGGER} from './src/features/default/constants'
