name: CI

on:
    workflow_dispatch:
    push:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    tests:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - name: Setup Environment
              uses: nowely/action-setup-node@v1

            - name: Run Tests
              run: pnpm test

    build:
        name: Build Package
        runs-on: ubuntu-latest
        steps:
            - name: Setup Environment
              uses: nowely/action-setup-node@v1

            - name: Run Build
              run: pnpm run build
