name: CI

on:
    workflow_dispatch:
    pull_request:
        branches: ['**']
    push:
        branches: [main, master]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    tests:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - name: Setup Environment
              uses: nowely/action-setup-node@v1

            - name: Install Playwright Browsers
              run: pnpm playwright install --with-deps --only-shell chromium

            - name: Run Tests
              run: pnpm test

    typecheck:
        name: Type Check
        runs-on: ubuntu-latest
        steps:
            - name: Setup Environment
              uses: nowely/action-setup-node@v1

            - name: Run Typecheck
              run: pnpm run typecheck

    lint:
        name: Lint Code
        runs-on: ubuntu-latest
        steps:
            - name: Setup Environment
              uses: nowely/action-setup-node@v1

            - name: Run Lint
              run: pnpm run lint

    build:
        name: Build Package
        runs-on: ubuntu-latest
        steps:
            - name: Setup Environment
              uses: nowely/action-setup-node@v1

            - name: Run Build
              run: pnpm run build
    format:
        name: Check Formatting
        runs-on: ubuntu-latest
        steps:
            - name: Setup Environment
              uses: nowely/action-setup-node@v1

            - name: Check Code Formatting
              run: pnpm run format
