name: Publish to npm

on: workflow_dispatch

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    publishing:
        name: Publishing
        runs-on: ubuntu-latest
        steps:
            - name: Setup Environment
              uses: nowely/action-setup-node@v1

            - name: Build Package
              run: pnpm run build

            - name: Setup npm registry
              run: |
                echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
                npm config set registry https://registry.npmjs.org/

            - id: publish
              name: Publish to npm
              shell: bash
              run: pnpm run publish
#            - if: steps.publish.outputs.type != 'none'
#              run: |
#                  echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
