name: Publish to npm

on:
    workflow_dispatch:
        inputs:
            release_type:
                description: 'Release type'
                required: true
                default: 'patch'
                type: choice
                options:
                    - major
                    - minor
                    - patch
                    - none

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    publishing:
        name: Publishing
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Setup Environment
              uses: nowely/action-setup-node@v1

            - name: Bump Version
              if: ${{ github.event.inputs.release_type != 'none' }}
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  cd packages/markput
                  pnpm version ${{ github.event.inputs.release_type }} --no-git-tag-version
                  cd ../..
                  VERSION=$(node -p "require('./packages/markput/package.json').version")
                  git commit -am "chore: bump version to $VERSION"
                  git push

            - name: Build Package
              run: pnpm run build

            - name: Setup npm registry
              run: |
                  echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
                  npm config set registry https://registry.npmjs.org/

            - id: publish
              name: Publish to npm
              shell: bash
              run: pnpm run publish

            - name: Create and Push Tag
              if: ${{ github.event.inputs.release_type != 'none' }}
              run: |
                  VERSION=$(node -p "require('./packages/markput/package.json').version")
                  git tag v$VERSION
                  git push origin v$VERSION
