name: Publish to npm

on: workflow_dispatch

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    publishing:
        name: Publishing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Setup Node.js 22.x
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                version: 10

            - name: Install Dependencies
              run: pnpm install --frozen-lockfile

            - name: Build Package
              run: pnpm run build

            - id: publish
              name: Publish to npm
              shell: bash
              run: pnpm run publish
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - if: steps.publish.outputs.type != 'none'
              run: |
                  echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
